spring:
  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: mysql

aws:
  redis:
    url:
    port: 6379
